package com.react.telink.ble

const val EVENT_DEVICE_FOUND = "EVENT_DEVICE_FOUND"

const val EVENT_SCANNING_TIMEOUT = "EVENT_SCANNING_TIMEOUT"

const val EVENT_PROVISIONING_START = "EVENT_PROVISIONING_START"

const val EVENT_PROVISIONING_SUCCESS = "EVENT_PROVISIONING_SUCCESS"

const val EVENT_PROVISIONING_FAILED = "EVENT_PROVISIONING_FAILED"

const val EVENT_BINDING_START = "EVENT_BINDING_START"

const val EVENT_BINDING_SUCCESS = "EVENT_BINDING_SUCCESS"

const val EVENT_BINDING_FAILED = "EVENT_BINDING_FAILED"

const val EVENT_SET_GROUP_SUCCESS = "EVENT_SET_GROUP_SUCCESS"

const val EVENT_SET_GROUP_FAILED = "EVENT_SET_GROUP_FAILED"

const val EVENT_REMOVE_GROUP_SUCCESS = "EVENT_REMOVE_GROUP_SUCCESS"

const val EVENT_REMOVE_GROUP_FAILED = "EVENT_REMOVE_GROUP_FAILED"

const val EVENT_SET_SCENE_SUCCESS = "EVENT_SET_SCENE_SUCCESS"

const val EVENT_SET_SCENE_FAILED = "EVENT_SET_SCENE_FAILED"

const val EVENT_REMOVE_SCENE_SUCCESS = "EVENT_REMOVE_SCENE_SUCCESS"

const val EVENT_REMOVE_SCENE_FAILED = "EVENT_REMOVE_SCENE_FAILED"

const val EVENT_SET_TRIGGER_SUCCESS = "EVENT_SET_TRIGGER_SUCCESS"

const val EVENT_SET_TRIGGER_FAILED = "EVENT_SET_TRIGGER_FAILED"

const val EVENT_RESET_NODE_SUCCESS = "EVENT_RESET_NODE_SUCCESS"

const val EVENT_DEVICE_STATE = "EVENT_DEVICE_STATE"
